### ISSUE TITLE
Manual installation -> Class not found

### ISSUE THREAD

**Issue by dmgawel** [soberwp/models#2]
Hi!

I'm currently working on a big project with a lot of legacy code and introducing Composer and Bedrock is in our backlog so I had to go with manual installation. Unfortunately it's not working. It seems that `dist` dir does not contain needed composer packages:

```
Warning: include(/var/www/public/wp-content/plugins/models/dist/composer/../hassankhan/config/src/Config.php): failed to open stream: No such file or directory in /var/www/public/wp-content/plugins/models/dist/composer/ClassLoader.php on line 440

Warning: include(): Failed opening '/var/www/public/wp-content/plugins/models/dist/composer/../hassankhan/config/src/Config.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/public/wp-content/plugins/models/dist/composer/ClassLoader.php on line 440

Fatal error: Class 'Noodlehaus\Config' not found in /var/www/public/wp-content/plugins/models/src/Loader.php on line 47
```

**Comment by darrenjacoby** [comment]
Hi @dmgawel, I will test the dist/ folder on my side and get back to you.  Perhaps the build process has failed.

**Comment by darrenjacoby** [comment]
Hi @dmgawel please try re-download the master/archive.zip.  I've updated the build process and tested, should be working now.

**Comment by dmgawel** [comment]
Works like a charm, thanks!

I think it would be a good idea to upload compressed zip file to github as a release artifact. This way you won't have to store external dependencies in `models` repository. Anyway, this issue is solved.
