### ISSUE TITLE
Ship with theme

### ISSUE THREAD

**Issue by dmgawel** [soberwp/models#4]
It would be perfect if models comes with ability to ship with theme as library, all the more so because theme folder is default place for model config files.

**Comment by darrenjacoby** [comment]
@dmgawel as a Composer package vs a plugin?

**Comment by dmgawel** [comment]
As a Composer package required by a theme (same as Sage consumes controller).

**Comment by darrenjacoby** [comment]
@dmgawel thinking about it more, I'm not sure that Models should ship as a theme dependency. If the user then disables the theme the post types/taxonomies then get removed from the WP backend.  

Having it as a mu-plugin allows for separation of concerns which I feel is better, allowing a developer to change themes without worrying about post types/taxonomies.  

I released [Unravel](https://github.com/soberwp/unravel) to further encourage separation of concerns for Model and Advanced Custom Field config files from the theme directory.

**Comment by darrenjacoby** [comment]
@dmgawel 

I'll be looking at options for both Intervention and Models as Sage dependencies this week. Closing for now.

**Comment by darrenjacoby** [comment]
@dmgawel you can now include Models from the Sage theme dir. 

```
composer require soberwp/models:1.0.5-p
```

**Comment by dmgawel** [comment]
That's great! Thank you!

**Comment by kaisermann** [comment]
Thank you very much for that! I understand why separating the models from the theme is a good thing, but, at least for my cases, the cpts/taxonomies are intricately related to the theme.

**Comment by alessioarzenton** [comment]
Hello, is it possible use soberwp/models and controller into a child theme (the parent theme is a sage starter theme)?
