### ISSUE TITLE
Using Models outside of sage

### ISSUE THREAD

**Issue by Pushplaybang** [soberwp/models#7]
Hi There

Is it possible to use the models packages as a theme dependancy outside of sage?  Not sure if I'm doing something silly, but I installed with composer and did the following with no errors, or results:

```php
require_once(__DIR__ . "./../vendor/soberwp/models/dist/autoload.php");

add_filter('sober/models/path', function () {
  return get_stylesheet_directory() . '/lib/models';
});
```
setup JSON files, but no dice, I assume I need to do something else to get this going.

Would I `use` the class, and invoke the loader?

**Comment by darrenjacoby** [comment]
Yeah, you would have to initialise Models. 

https://github.com/soberwp/models/blob/master/models.php#L30

You could probably just require `models.php` instead of the autoloader, as `models.php` is doing that for you. 

Try `require_once(__DIR__ . "./../vendor/soberwp/models/models.php");`

**Comment by darrenjacoby** [comment]
Cool to see that you're also from Cape Town!

**Comment by Pushplaybang** [comment]
thanks, @darrenjacoby  - yeah cape town based, but heading for Jozi soon with all this water nonsense.

So yeah, basically I was being a bit silly, haven't php'd in years so finding my feet again.  I should probably just switch to sage, but I'm halfway through this project, just setup blade templating to bring some sanity as well.  0_0

What I landed up doing:

```php
// in functions.php
require_once(__DIR__ . "/vendor/autoload.php");

// in lib/config/models.php
use Sober\Models\Loader;

add_action('init', function () {
    new Loader();
});

add_filter('sober/models/path', function () {
  return get_template_directory() . '/lib/models/';
});

```

pretty straightforward.  Thanks for the help.
