### ISSUE TITLE
Extended methods not being used

### ISSUE THREAD

**Issue by kaisermann** [soberwp/models#9]
The package version (at least the version `1.0.6-p`) isn't using the `extended` version of the register methods. 

![image](https://user-images.githubusercontent.com/12702016/36310610-ca510316-130f-11e8-9987-6305357c3f49.png)

![image](https://user-images.githubusercontent.com/12702016/36310620-d1b0ea5e-130f-11e8-9681-0d0abe3f2aa2.png)

![image](https://user-images.githubusercontent.com/12702016/36310642-db3a67ee-130f-11e8-8600-0aba0c7a78bb.png)

**Comment by darrenjacoby** [comment]
It was causing issues in the previous version, so removed the extended version. Happy to accept a PR for the extended version.
